namespace main_GUI
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
    // must be declared for WinUI controls to reference it 
        Microsoft.UI.Xaml.Controls.NavigationViewItem HelpItem;
    }
}
