namespace main_GUI
{
    [bindable]
    [default_interface]
    runtimeclass SimulationViewItem 
    {
        SimulationViewItem();

        //String Date;
        //String Amount;
        //Double Height;
    }
}
